#OSS
novel:
  file:
    endpoint:  #不同的服务器，地址不同
    key-id:  #去OSS控制台获取
    key-secret:  #去OSS控制台获取
    bucket-name:  #这个自己创建bucket时的命名，控制台创建也行，代码创建也行
    file-host:  #文件路径
    web-url:  #OSS文件的web访问地址